spring.application.name=FakeCommerce

spring.datasource.url=jdbc:mysql://localhost:3306/fakecommerce
spring.datasource.username=root
spring.datasource.password=aA@888888
#spring.datasouce.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.flyway.baselineOnMigrate=true

spring.flyway.url=jdbc:mysql://localhost:3306/fakecommerce

spring.flyway.user=root

spring.flyway.password=aA@888888

spring.data.redis.host=root
spring.data.redis.port=6379


